# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='endereco',
            field=models.CharField(default='#', max_length=120, null=True),
        ),
    ]
